### ISSUE TITLE
Setting reference image causes "RuntimeError: Input type (float) and bias type (c10::Half) should be the same"

### ISSUE THREAD

**Issue by listelin** [navervision/Graphit#1]
In Image to Image, when I set Source Image and Reference Image and Generate Image, I get the error "RuntimeError: Input type (float) and bias type (c10::Half) should be the same". error and cannot generate the image.

* When I use a cpu, it works fine, but when I use a gpu (Geforce 2080Ti), the error occurs.
* If Reference Image is not used, the error does not occur.

```
CompoDiff sampling loop: 100%|██████████| 24/24 [00:00<00:00, 28.93it/s]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gradio/routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/site-packages/gradio/blocks.py", line 1015, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.10/site-packages/gradio/blocks.py", line 833, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/app/demo_editor.py", line 575, in generate
    images = model_dict['pipe'](text_input,
  File "/usr/local/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/app/demo_editor.py", line 192, in __call__
    image_latents = self.prepare_image_latents(
  File "/app/demo_editor.py", line 87, in prepare_image_latents
    image_latents = self.vae.encode(image).latent_dist.mode()
  File "/usr/local/lib/python3.10/site-packages/diffusers/models/autoencoder_kl.py", line 164, in encode
    h = self.encoder(x)
  File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/diffusers/models/vae.py", line 109, in forward
    sample = self.conv_in(sample)
  File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Input type (float) and bias type (c10::Half) should be the same
```

**Comment by geonm** [comment]
@listelin 

I'm sorry for the inconvenience.

I've made the corrections through this PR https://github.com/navervision/Graphit/pull/2, but please let me know if there are still errors by leaving a comment.

**Comment by geonm** [comment]
@listelin 

We also fixed the HuggingFace demo https://huggingface.co/spaces/navervision/Graphit-SD

Thank you for reporting this issue!
